config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'playlists#index'
  resources :playlists, only: %i[index new create edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, :genre, :description, presence: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[edit update]

  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @playlist.update(playlist_params)
    redirect_to root_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :genre, :description, :photo)
  end

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPlaylist</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
      <%= link_to root_path, class: "navbar-brand" do %>
        My Playlists
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "New Playlist", new_playlist_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/playlists/edit.html.erb
<%= simple_form_for(@playlist) do |f| %>
  <%= f.input :name%>
  <%= f.input :genre%>
  <%= f.input :description%>
  <%= f.input :photo, as: :file%>
  <%= f.submit %>
<% end %>
<%= link_to "Back", root_path %>

app/views/playlists/index.html.erb
<div class="cards">
  <% @playlists.each do |playlist|%>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path playlist.photo.key, crop: :fill %>')">
      <%= playlist.name %>
    </div>
  <% end %>
</div>

app/views/playlists/new.html.erb
<%= simple_form_for(@playlist) do |f| %>
  <%= f.input :name%>
  <%= f.input :genre%>
  <%= f.input :description%>
  <%= f.input :photo, as: :file%>
  <%= f.submit %>
<% end %>